script/ptl-tool.py: Fixed detached from origin/master
batrick/ceph pull request #3
Opened 2017-10-03 12:11 UTC by joscollin

The following command always leaves "detached from origin/master"
    
$ env PTL_TOOL_BASE_PATH=refs/remotes/upstream/ src/script/ptl-tool.py --base master 1234567 2345678
    
Signed-off-by: Jos Collin <jcollin@redhat.com>

2017-10-04 23:52 UTC, batrick requested changes
Getting this error:

````
$ src/script/ptl-tool.py --base master --label - 17678 18109
Detaching HEAD onto base: master
Traceback (most recent call last):
  File "src/script/ptl-tool.py", line 272, in <module>
    main()
  File "src/script/ptl-tool.py", line 269, in main
    return build_branch(args)
  File "src/script/ptl-tool.py", line 129, in build_branch
    git.Git().checkout(base)
  File "/usr/lib/python2.7/site-packages/git/cmd.py", line 551, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/git/cmd.py", line 1010, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/lib/python2.7/site-packages/git/cmd.py", line 821, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git checkout master
  stderr: 'error: pathspec 'master' did not match any file(s) known to git.'
````

I don't really understand what this patch is trying to do.

2017-10-05 04:37 UTC, joscollin commented
@batrick The reason for creating this patch is I'm getting the below issue after using ptl-tool.py. See **(detached from origin/master)** after using ptl-tool.py. Is this an expected behaviour ?

```
jcollin@smithi042:~/ptl-tool/test$ src/script/ptl-tool.py --base master --label wip-badone-testing 18108
Detaching HEAD onto base: master
Merging PR #18108
Labeled PR #18108 wip-badone-testing
Created branch wip-jcollin-testing-20171005
Created tag testing/wip-jcollin-testing-20171005_02
jcollin@smithi042:~/ptl-tool/test$ git branch
* (detached from origin/master)
  fix-comment
  fix-detached
  fix-label
  master
  msg-fix
  ptl-tool-2
  wip-jcollin-testing-20171005
```

2017-10-05 14:50 UTC, batrick commented
Leaving HEAD detached is intended when `--branch HEAD`. We should checkout the branch as a last step of `build_branch` if it is not `HEAD`.

2017-10-06 18:54 UTC, closed without merging

2017-10-06 18:54 UTC, batrick commented
https://github.com/ceph/ceph/pull/18157